name: spend_analytics
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # device related
  package_info: ^2.0.0

  # UI related
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_screenutil: ^4.0.4+1
  flutter_launcher_icons: ^0.9.0
  fl_chart: ^0.35.0
  toast: ^0.1.5
 

  # DB related
  path_provider: ^1.6.28
  shared_preferences: ^0.5.12
  sqflite: ^1.3.2+3
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sp_logo.png"
  adaptive_icon_background: "assets/images/logo_back.png"
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  fonts: 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900
