// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:spend_analytics/core/enums/budget_period.dart';
import 'package:spend_analytics/core/enums/expense_type.dart';
import 'package:spend_analytics/core/enums/payment_type.dart';
import 'package:spend_analytics/core/enums/recurring_frequency.dart';
import 'package:spend_analytics/core/enums/rule_type.dart';
import 'package:spend_analytics/core/enums/subscription_tier.dart';
import 'package:spend_analytics/core/sync/models/sync_operation_model.dart';
import 'package:spend_analytics/features/budget/data/models/budget_model.dart';
import 'package:spend_analytics/features/categories/data/models/category_model.dart';
import 'package:spend_analytics/features/expense/data/models/expense_model.dart';
import 'package:spend_analytics/features/notifications/data/models/notification_event_model.dart';
import 'package:spend_analytics/features/recurring/data/models/recurring_model.dart';
import 'package:spend_analytics/features/rules/data/models/rule_model.dart';
import 'package:spend_analytics/features/settings/data/models/settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetModelAdapter());
    registerAdapter(BudgetPeriodAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(ExpenseTypeAdapter());
    registerAdapter(NotificationEventModelAdapter());
    registerAdapter(PaymentTypeAdapter());
    registerAdapter(RecurringFrequencyAdapter());
    registerAdapter(RecurringModelAdapter());
    registerAdapter(RuleModelAdapter());
    registerAdapter(RuleTypeAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SubscriptionTierAdapter());
    registerAdapter(SyncOperationModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetModelAdapter());
    registerAdapter(BudgetPeriodAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(ExpenseTypeAdapter());
    registerAdapter(NotificationEventModelAdapter());
    registerAdapter(PaymentTypeAdapter());
    registerAdapter(RecurringFrequencyAdapter());
    registerAdapter(RecurringModelAdapter());
    registerAdapter(RuleModelAdapter());
    registerAdapter(RuleTypeAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SubscriptionTierAdapter());
    registerAdapter(SyncOperationModelAdapter());
  }
}
