import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:screenx/screenx.dart';
import 'package:spend_analytics/core/config/app_config.dart';
import 'package:spend_analytics/core/di/dependency_injection.dart';
import 'package:spend_analytics/core/di/injection.dart';
import 'package:spend_analytics/core/routes/app_routes.dart';
import 'package:spend_analytics/core/services/biometric_lock_service.dart';
import 'package:spend_analytics/core/storage/hive_service.dart';
import 'package:spend_analytics/core/theme/app_theme.dart';
import 'package:spend_analytics/core/theme/theme_service.dart';
import 'package:spend_analytics/features/auth/biometric_lock_screen.dart';
import 'package:spend_analytics/firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Load environment config (.env / envified)
  await AppConfig.init();

  // 2. Firebase must be ready before Get_It modules and GetX services.
  //    FirebaseBootstrapService.init() guards against double-init via
  //    Firebase.apps.isEmpty, so this call is safe alongside the existing DI.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Hive CE: open encrypted boxes before any data source is accessed.
  await HiveService.instance.init();

  // 4. Get_It + Injectable graph (v4 architecture).
  //    injection.config.dart is generated by build_runner — run:
  //      fvm flutter pub run build_runner build --delete-conflicting-outputs
  await configureDependencies(Env.prod);

  // 5. GetX DI — kept alongside until Phase 7 removes it.
  await DependencyInjection.init();

  // 6. Phase 1h: DataMigrationService.runIfNeeded() will be inserted here
  //    once it is implemented. It reads Drift data → writes to Hive CE boxes
  //    that are now open (step 3 above).

  runApp(const _LifecycleObserver(child: SpendAnalyticsApp()));
}

/// Observes app lifecycle to trigger biometric lock on resume.
class _LifecycleObserver extends StatefulWidget {
  const _LifecycleObserver({required this.child});

  final Widget child;

  @override
  State<_LifecycleObserver> createState() => _LifecycleObserverState();
}

class _LifecycleObserverState extends State<_LifecycleObserver>
    with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _checkBiometricLock();
    }
  }

  void _checkBiometricLock() {
    if (!Get.isRegistered<BiometricLockService>()) return;
    final lockService = Get.find<BiometricLockService>();
    if (lockService.shouldLock) {
      // Use Get.dialog so it overlays any current route non-dismissibly
      Get.dialog<void>(
        const BiometricLockScreen(),
        barrierDismissible: false,
        barrierColor: Colors.black.withValues(alpha: 0.6),
      );
    }
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

class SpendAnalyticsApp extends StatelessWidget {
  const SpendAnalyticsApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeMode =
        Get.isRegistered<ThemeService>()
            ? Get.find<ThemeService>().themeMode.value
            : ThemeMode.system;
    return GetMaterialApp(
      title: AppConfig.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: themeMode,
      initialRoute: AppRoutes.splash,
      getPages: AppRoutes.pages,
      defaultTransition: Transition.fadeIn,
      enableLog: kDebugMode,
      // ScreenXLayout initialises ScreenX.sp/dp/wp/hp/bp globally.
      builder: (context, child) =>
          ScreenXLayout(child: child ?? const SizedBox.shrink()),
    );
  }
}

