import 'dart:io';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:spend_analytics/core/error/failures.dart';
import 'package:spend_analytics/features/analytics/domain/models/reports_data.dart';
import 'package:spend_analytics/features/expense/domain/entities/expense_entity.dart';
import 'package:spend_analytics/features/expense/domain/usecases/watch_expenses_use_case.dart';
import 'package:spend_analytics/features/settings/domain/usecases/export_csv_use_case.dart';
import 'package:spend_analytics/features/settings/domain/usecases/export_pdf_use_case.dart';

import 'reports_event.dart';
import 'reports_state.dart';

@injectable
class ReportsBloc extends Bloc<ReportsEvent, ReportsState> {
  ReportsBloc(
    this._watchExpenses,
    this._exportCsv,
    this._exportPdf,
  ) : super(const ReportsState.initial()) {
    on<ReportsLoad>(_onLoad);
    on<ReportsChangeRange>(_onChangeRange);
    on<ReportsExport>(_onExport);
  }

  final WatchExpensesUseCase _watchExpenses;
  final ExportCsvUseCase _exportCsv;
  final ExportPdfUseCase _exportPdf;

  Future<void> _onLoad(ReportsLoad event, Emitter<ReportsState> emit) async {
    emit(const ReportsState.loading());
    await emit.forEach(
      _watchExpenses(event.userId),
      onData: (result) => result.fold(
        (f) => ReportsState.failure(failure: f),
        (expenses) => ReportsState.loaded(
          allExpenses: expenses,
          selectedRange: event.range,
          data: _computeReportsData(expenses, event.range),
        ),
      ),
      onError: (e, _) => ReportsState.failure(
        failure: Failure.unknown(e.toString(), cause: e),
      ),
    );
  }

  void _onChangeRange(ReportsChangeRange event, Emitter<ReportsState> emit) {
    // state.maybeMap is generated by Freezed — pre-build-runner errors expected
    state.maybeMap(
      loaded: (s) => emit(ReportsState.loaded(
        allExpenses: s.allExpenses,
        selectedRange: event.range,
        data: _computeReportsData(s.allExpenses, event.range),
      )),
      orElse: () {},
    );
  }

  Future<void> _onExport(ReportsExport event, Emitter<ReportsState> emit) async {
    emit(const ReportsState.exporting());
    final now = DateTime.now();
    try {
      if (event.format == 'csv') {
        final result = await _exportCsv(
          userId: event.userId,
          month: now.month,
          year: now.year,
        );
        await result.fold(
          (f) async => emit(ReportsState.failure(failure: f)),
          (csvString) async {
            final dir = await getTemporaryDirectory();
            final file =
                File('${dir.path}/report_${now.year}_${now.month}.csv');
            await file.writeAsString(csvString);
            await SharePlus.instance.share(ShareParams(
              files: [XFile(file.path, mimeType: 'text/csv')],
              subject: 'Spend Analytics Report',
            ));
            emit(const ReportsState.exported());
          },
        );
      } else {
        final result = await _exportPdf(
          userId: event.userId,
          month: now.month,
          year: now.year,
        );
        await result.fold(
          (f) async => emit(ReportsState.failure(failure: f)),
          (bytes) async {
            final dir = await getTemporaryDirectory();
            final file =
                File('${dir.path}/report_${now.year}_${now.month}.pdf');
            await file.writeAsBytes(bytes);
            await SharePlus.instance.share(ShareParams(
              files: [XFile(file.path, mimeType: 'application/pdf')],
              subject: 'Spend Analytics Report',
            ));
            emit(const ReportsState.exported());
          },
        );
      }
    } catch (e) {
      emit(ReportsState.failure(
          failure: Failure.unknown(e.toString(), cause: e)));
    }
  }

  ReportsData _computeReportsData(
      List<ExpenseEntity> expenses, String range) {
    final filtered = _filterByRange(expenses, range);
    if (filtered.isEmpty) return ReportsData.empty(range);
    // TODO(Phase 3): Port AnalyticsController chart/category/merchant computation here
    return ReportsData.empty(range);
  }

  List<ExpenseEntity> _filterByRange(
      List<ExpenseEntity> expenses, String range) {
    final now = DateTime.now();
    final DateTime cutoff;
    switch (range) {
      case 'week':
        cutoff = now.subtract(const Duration(days: 7));
      case '3m':
        cutoff = DateTime(now.year, now.month - 2, 1);
      case 'year':
        cutoff = DateTime(now.year, 1, 1);
      case 'all':
        return expenses;
      default: // 'month'
        cutoff = DateTime(now.year, now.month, 1);
    }
    return expenses
        .where((e) => e.transactionDate.isAfter(cutoff))
        .toList();
  }
}
